name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Display-runner-information:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install python requirements
        run: pip install -r requirements.txt
      - name: Run pylint
        run: pylint **/*.py
      - name: Run black
      - run: black .
